/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MantraRouteImport } from './routes/mantra'
import { Route as MandaliRouteImport } from './routes/mandali'
import { Route as JaapRouteImport } from './routes/jaap'
import { Route as ChalisaRouteImport } from './routes/chalisa'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MandaliJoinRouteImport } from './routes/mandali_.join'
import { Route as MandaliCreateRouteImport } from './routes/mandali_.create'
import { Route as AdminUsersRouteImport } from './routes/admin_.users'
import { Route as AdminContentRouteImport } from './routes/admin_.content'
import { Route as AdminContentNewRouteImport } from './routes/admin_.content_.new'
import { Route as AdminContentIdRouteImport } from './routes/admin_.content_.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MantraRoute = MantraRouteImport.update({
  id: '/mantra',
  path: '/mantra',
  getParentRoute: () => rootRouteImport,
} as any)
const MandaliRoute = MandaliRouteImport.update({
  id: '/mandali',
  path: '/mandali',
  getParentRoute: () => rootRouteImport,
} as any)
const JaapRoute = JaapRouteImport.update({
  id: '/jaap',
  path: '/jaap',
  getParentRoute: () => rootRouteImport,
} as any)
const ChalisaRoute = ChalisaRouteImport.update({
  id: '/chalisa',
  path: '/chalisa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MandaliJoinRoute = MandaliJoinRouteImport.update({
  id: '/mandali_/join',
  path: '/mandali/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MandaliCreateRoute = MandaliCreateRouteImport.update({
  id: '/mandali_/create',
  path: '/mandali/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin_/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentNewRoute = AdminContentNewRouteImport.update({
  id: '/admin_/content_/new',
  path: '/admin/content/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentIdRoute = AdminContentIdRouteImport.update({
  id: '/admin_/content_/$id',
  path: '/admin/content/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chalisa': typeof ChalisaRoute
  '/jaap': typeof JaapRoute
  '/mandali': typeof MandaliRoute
  '/mantra': typeof MantraRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/users': typeof AdminUsersRoute
  '/mandali/create': typeof MandaliCreateRoute
  '/mandali/join': typeof MandaliJoinRoute
  '/admin/content/$id': typeof AdminContentIdRoute
  '/admin/content/new': typeof AdminContentNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chalisa': typeof ChalisaRoute
  '/jaap': typeof JaapRoute
  '/mandali': typeof MandaliRoute
  '/mantra': typeof MantraRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/users': typeof AdminUsersRoute
  '/mandali/create': typeof MandaliCreateRoute
  '/mandali/join': typeof MandaliJoinRoute
  '/admin/content/$id': typeof AdminContentIdRoute
  '/admin/content/new': typeof AdminContentNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chalisa': typeof ChalisaRoute
  '/jaap': typeof JaapRoute
  '/mandali': typeof MandaliRoute
  '/mantra': typeof MantraRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/admin_/content': typeof AdminContentRoute
  '/admin_/users': typeof AdminUsersRoute
  '/mandali_/create': typeof MandaliCreateRoute
  '/mandali_/join': typeof MandaliJoinRoute
  '/admin_/content_/$id': typeof AdminContentIdRoute
  '/admin_/content_/new': typeof AdminContentNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chalisa'
    | '/jaap'
    | '/mandali'
    | '/mantra'
    | '/onboarding'
    | '/progress'
    | '/settings'
    | '/admin/content'
    | '/admin/users'
    | '/mandali/create'
    | '/mandali/join'
    | '/admin/content/$id'
    | '/admin/content/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/chalisa'
    | '/jaap'
    | '/mandali'
    | '/mantra'
    | '/onboarding'
    | '/progress'
    | '/settings'
    | '/admin/content'
    | '/admin/users'
    | '/mandali/create'
    | '/mandali/join'
    | '/admin/content/$id'
    | '/admin/content/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chalisa'
    | '/jaap'
    | '/mandali'
    | '/mantra'
    | '/onboarding'
    | '/progress'
    | '/settings'
    | '/admin_/content'
    | '/admin_/users'
    | '/mandali_/create'
    | '/mandali_/join'
    | '/admin_/content_/$id'
    | '/admin_/content_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChalisaRoute: typeof ChalisaRoute
  JaapRoute: typeof JaapRoute
  MandaliRoute: typeof MandaliRoute
  MantraRoute: typeof MantraRoute
  OnboardingRoute: typeof OnboardingRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminUsersRoute: typeof AdminUsersRoute
  MandaliCreateRoute: typeof MandaliCreateRoute
  MandaliJoinRoute: typeof MandaliJoinRoute
  AdminContentIdRoute: typeof AdminContentIdRoute
  AdminContentNewRoute: typeof AdminContentNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mantra': {
      id: '/mantra'
      path: '/mantra'
      fullPath: '/mantra'
      preLoaderRoute: typeof MantraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandali': {
      id: '/mandali'
      path: '/mandali'
      fullPath: '/mandali'
      preLoaderRoute: typeof MandaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jaap': {
      id: '/jaap'
      path: '/jaap'
      fullPath: '/jaap'
      preLoaderRoute: typeof JaapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chalisa': {
      id: '/chalisa'
      path: '/chalisa'
      fullPath: '/chalisa'
      preLoaderRoute: typeof ChalisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandali_/join': {
      id: '/mandali_/join'
      path: '/mandali/join'
      fullPath: '/mandali/join'
      preLoaderRoute: typeof MandaliJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandali_/create': {
      id: '/mandali_/create'
      path: '/mandali/create'
      fullPath: '/mandali/create'
      preLoaderRoute: typeof MandaliCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/users': {
      id: '/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/content': {
      id: '/admin_/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/content_/new': {
      id: '/admin_/content_/new'
      path: '/admin/content/new'
      fullPath: '/admin/content/new'
      preLoaderRoute: typeof AdminContentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/content_/$id': {
      id: '/admin_/content_/$id'
      path: '/admin/content/$id'
      fullPath: '/admin/content/$id'
      preLoaderRoute: typeof AdminContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChalisaRoute: ChalisaRoute,
  JaapRoute: JaapRoute,
  MandaliRoute: MandaliRoute,
  MantraRoute: MantraRoute,
  OnboardingRoute: OnboardingRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminUsersRoute: AdminUsersRoute,
  MandaliCreateRoute: MandaliCreateRoute,
  MandaliJoinRoute: MandaliJoinRoute,
  AdminContentIdRoute: AdminContentIdRoute,
  AdminContentNewRoute: AdminContentNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
